name: Update wp.org readme and assets

on:
  push:
    branches:
      - main
    paths:
      - "readme.txt"
      - ".wordpress-org/**"

jobs:
  assets:
    name: Sync readme and assets to wp.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update readme and assets
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: batchpilot
