name: Deploy to WordPress.org

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to wp.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer:v2
          coverage: none

      - name: Install production Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --no-progress

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: batchpilot
